// SPDX-License-Identifier: GPL-2.0-or-later
// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields are version.txt (MAJOR.MINOR) and build_number.txt.
#ifndef VERSION_H
#define VERSION_H

#define FW_VERSION_MAJOR  0
#define FW_VERSION_MINOR  14
#define FW_VERSION_BUILD  90

#define FW_VERSION_STRING "0.14.90"
#define FW_BUILD_DATE     "2026-05-11 11:56:08"

#endif // VERSION_H
